### ISSUE TITLE
Two oracle instance in one serwer.

### ISSUE THREAD

**Issue by edta6** [sergiotocalini/zabora#1]
How to monitor two oracle databases or more on one server?
Can this be done without creating a new user on the system?

**Comment by sergiotocalini** [comment]
Indeed, you just need to pass the Oracle ID as a parameter and it has to be setup in the oratab.

**Comment by d1nd141** [comment]
How do you manage to monitor 2 or more different DB on one server (with one single agent) ?
You can only add the template once to the host.
Copying the items to the same host does not work either, duplicate key.

Thanks

**Comment by edta6** [comment]
Use macro in Zabbix then create two item by clone template item to othe item. 
Work Fine.
