### ISSUE TITLE
Monitore Oracle Server 11g with Zabora scripts

### ISSUE THREAD

**Issue by igorxingu** [sergiotocalini/zabora#10]
Hello Sergio and all. 
The Sergio Zabora Project and scripts are ok and work well. 
I tried to find my support case here, but I dind´t find.

For the Zabora scripts work in Redhat 7, you need to change this oracle files permissions:

# cd /oracle/product/11.2.0.4/dbhome_1/bin/
# chown 6751 oracle oracleO oradism

Only after the changes oracle files that Zabbix started to monitor correctly.

Hope this help. Thanks. 
Igor Costa

**Comment by sergiotocalini** [comment]
Hi @igorxingu,

Thanks for opening the issue.
It is very helpful I will include it in the documentation.

Regards,
Sergio
