### ISSUE TITLE
the Key zabora[{$ORACLE_SID},db_metric,'Response Time Per Txn'] Fail to work

### ISSUE THREAD

**Issue by leoowu** [sergiotocalini/zabora#2]
[root@ip-10-5-0-14 ~]#  zabbix_get -s 10.5.40.12 -p 10050   -k zabora[{$ORACLE_SID},db_metric,'Response Time Per Txn']
ZBX_NOTSUPPORTED: Special characters "\, ', ", `, *, ?, [, ], {, }, ~, $, !, &, ;, (, ), <, >, |, #, @, 0x0a" are not allowed in the parameters.

zabibx 3.4

**Comment by sergiotocalini** [comment]
You should replace the string {$ORACLE_SID} with your ORACLE SID and if you want to pass special characters you need to setup in your zabbix agent to allow that.

**Comment by lfavero** [comment]
I've the same issue on zabbix agent 
![immagine](https://user-images.githubusercontent.com/46285687/105741277-63adab80-5f3a-11eb-99ce-d90d9662f611.png)

Can you explain how is possibile to configure the Oracle_Sid in the rght way ? 
Thanks 
Luigi

**Comment by sergiotocalini** [comment]
Hi @lfavero!

This issue is related with your zabbix agent configuration and happens when you pass those special characters. Please be sure that your ORACLE_SID doesn't have this kind of parameter.

Best,
Sergio
