### ISSUE TITLE
Use problem

### ISSUE THREAD

**Issue by Vellis-it** [sergiotocalini/zabora#4]
Configured on the host. Imported a template to Zabbix.
Of all the data elements, only the database version works, all the others marked "Not supported", when you hover we get an error:
Value "SQL*Plus: Release 12.2.0.1.0 Production Copyright (c) 1982, 2016, Oracle. All rights reserved. Use SQL*Plus to execute SQL, PL/SQL and SQL*Plus statements. Usage 1: sqlplus -H | -V -H Displays the SQL*Plus version and the usage help. -V Displays the SQL*Plus version. Usage 2: sqlplus [ [<option>] [{logon | /nolog}] [<start>] ] <option> is: [-AC] [-C <version>] [-L] [-M "<options>"] [-NOLOGINTIME] [-R <level>] [-S] -AC Enable Application Continuity. -C <version> Sets the compatibility of affected commands to the version specified by <version>. The version has the form "x.y[.z]". For example, -C 10.2.0 -L Attempts to log on just once, instead of reprompting on error. -M "<options>" Sets automatic HTML or CSV markup of output. The options have the form: {HTML html_options|CSV csv_options} See SQL*Plus User's Guide for detailed HTML and CSV options. -NOLOGINTIME Don't display Last Successful Login Time. -R <level> Sets restricted mode to disable SQL*Plus commands that interact with the file system. The level can be 1, 2 or 3. The most restrictive is -R 3 which disables all user commands interacting with the file system. -S Sets silent mode which suppresses the display of the SQL*Plus banner, prompts, and echoing of commands. <logon> is: {<username>[/<password>][@<connect_identifier>] | / } [AS {SYSDBA | SYSOPER | SYSASM | SYSBACKUP | SYSDG | SYSKM | SYSRAC}] [EDITION=value] Specifies the database account username, password and connect identifier for the database connection. Without a connect identifier, SQL*Plus connects to the default database. The AS SYSDBA, AS SYSOPER, AS SYSASM, AS SYSBACKUP, AS SYSDG, AS SYSKM and AS SYSRAC options are database administration privileges. <connect_identifier> can be in the form of Net Service Name or Easy Connect. @[<net_service_name> | [//]Host[:Port]/<service_name>] <net_service_name> is a simple name for a service that resolves to a connect descriptor. Example: Connect to database using Net Service Name and the database net service name is ORCL. sqlplus myusername/mypas

**Comment by sergiotocalini** [comment]
Hi @Vellis-it 
Thanks for your message.
It seems that you are missing the username and password to connect via sqlplus.
Please check the README file and you will be able to install it correctly.
Regards,
Sergio
